name: Test

on:
  push: ~
  workflow_dispatch: ~

env:
  PHP_VERSION: '8.2'
  GIT_DISCOVERY_ACROSS_FILESYSTEM: true

jobs:
  static-tests:
    name: "Running static tests"
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container: giuseppemorelli/php-ci-cd:8.2

    steps:
      -   uses: actions/checkout@v2

      -   name: Validate composer.json
          run: composer validate --ansi --no-check-publish

      -   name: Get Composer cache directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      -   name: Cache Composer
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-php-${{ env.PHP_VERSION }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-${{ env.PHP_VERSION }}-composer-

      -   name: Composer install for tests
          run: composer install --verbose --prefer-dist --no-progress --no-interaction --optimize-autoloader --no-suggest

      -   name: Run tests
          run: composer test-static
